# Generated by Django 4.2.1 on 2023-06-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
