# Generated by Django 4.2.1 on 2023-06-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='city_or_reg',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='possessiveness',
            field=models.CharField(choices=[('Государственный', 'Государственный'), ('Частный', 'Частный')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='region',
            field=models.CharField(choices=[('Иссык-Кульская', 'Иссык-Кульская'), ('Нарынская', 'Нарынская'), ('Чуйская', 'Чуйская'), ('Таласская', 'Таласская'), ('Джалал-Абадская', 'Джалал-Абадская'), ('Ошская', 'Ошская'), ('Баткенская', 'Баткенская')], max_length=100, null=True),
        ),
    ]
