# Generated by Django 4.2.1 on 2023-06-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_institute_city_or_reg_institute_possessiveness_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
