# Generated by Django 4.2.1 on 2023-06-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_profile_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streets',
            name='contractor',
        ),
        migrations.DeleteModel(
            name='Contractors',
        ),
        migrations.DeleteModel(
            name='Streets',
        ),
    ]
